services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=hw_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hw_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
